name: "Package"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
env:
  DEFAULT_NODE_VERSION: 25.x
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
jobs:
  Definitions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      DEFAULT_NODE_VERSION: ${{ env.DEFAULT_NODE_VERSION }}
    steps:
      - run: echo "Preparing definitions..."

  Test:
    needs: [ Definitions ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      checks: write
      id-token: write
    name: Testes (os ${{matrix.os}})(node v${{ matrix.node-version }})
    strategy:
      max-parallel: 1
      matrix:
        os: [ "ubuntu-latest" ]
        node-version: [ "20.x" ]
    steps:
      - uses: actions/checkout@v6
        name: Checkout
      - uses: actions/setup-node@v6
        name: Setup Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./pacote/package-lock.json"
      - name: Run npm ci
        run: npm ci
        working-directory: ./pacote
      - name: Run tests
        run: npm test
        working-directory: ./pacote

      - name: Test Report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: Testes (os ${{matrix.os}})(node v${{ matrix.node-version }}) - Resultados
          path: reports/junit.xml
          reporter: jest-junit
          working-directory: ./pacote

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          name: code-coverage-report-node-${{matrix.node-version}}
          files: ./coverage/lcov.info
          report_type: coverage
          verbose: true
          working-directory: ./pacote

      - name: Upload test results to Codecov
        uses: codecov/codecov-action@v6
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          name: test-results-node-${{matrix.node-version}}
          files: ./reports/junit.xml
          report_type: test_results
          verbose: true
          working-directory: ./pacote

  Build:
    needs: [ Test ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - uses: actions/checkout@v6
        name: Checkout
      - uses: actions/setup-node@v6
        name: Setup Node.js
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "./pacote/package-lock.json"
      - name: Copy package required files
        run: |
          cp -f ./README.md ./pacote/README.md
          cp -f ./LICENSE ./pacote/LICENSE

      - name: Run npm ci
        run: npm ci
        working-directory: ./pacote
      - name: Run build
        run: npm run build
        working-directory: ./pacote
      - name: Run npm pack
        run: npm pack
        working-directory: ./pacote
      - name: Extract package
        run: tar -xvf *.tgz
        working-directory: ./pacote
      - name: Archive build
        uses: actions/upload-artifact@v7
        with:
          name: package
          path: "./pacote/package"
      - name: Archive docs
        uses: actions/upload-artifact@v7
        with:
          name: docs
          path: "./pacote/docs"

  BuildExemplo:
    needs: [ Test ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - uses: actions/checkout@v6
        name: Checkout
      - uses: actions/setup-node@v6
        name: Setup Node.js
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "./exemplos/angular_app/package-lock.json"

      - name: Run npm ci
        run: npm ci
        working-directory: ./exemplos/angular_app
      - name: Run build
        run: |
          npm run build -- --output-path docs-angular --base-href /impostos-brasil/angular_app/
        working-directory: ./exemplos/angular_app
      - name: Archive docs
        uses: actions/upload-artifact@v7
        with:
          name: angular_app
          path: "./exemplos/angular_app/"

  check-npm-version:
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        name: Setup Node.js
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "./pacote/package-lock.json"
          package-manager-cache: false

      - name: Obter versão do package.json
        id: version
        working-directory: ./pacote
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Verificar se a versão já existe no NPM
        working-directory: ./pacote
        run: |
          echo "Verificando se a versão $VERSION já está publicada..."
          if npm view $(node -p "require('./package.json').name")@$VERSION version > /dev/null 2>&1; then
            echo "❌ A versão $VERSION já existe no NPM. Interrompendo pipeline."
            exit 1
          else
            echo "✅ Versão $VERSION ainda não publicada."
          fi

  Deploy-NPM:
    needs: [ check-npm-version ]
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/impostos-brasil
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: package
      - uses: actions/setup-node@v6
        name: Setup Node.js
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
          package-manager-cache: false
      - run: find .
        name: List package files
      - name: Run npm publish
        run: npm publish --provenance --access public --ignore-scripts

  Deploy-docs:
    needs: [ Deploy-NPM, BuildExemplo ]
    environment:
      name: Documentacao
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: false
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          name: docs
          path: ./docs
      - uses: actions/download-artifact@v8
        with:
          name: angular_app
          path: ./docs/angular_app/

      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          # Upload entire repository
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
